import java.util.Scanner;
public class Hello_World {
   public static void main(String[]args)/*must have a class, main is required in java*/
   {
   //tells System to use its output facilities and print the contents of the string
   System.out.println("Hello World");
   System.out.println("Programming is great fun!");
   
   }
}
class Simple {
   public static void main(String[] args)
   {
   System.out.print("This is being");
   System.out.print(" printed out");
   System.out.println(" on multiple lines.");
   System.out.print("This will have a newline.\n"); //  \n means new line
   System.out.print("These are our top sellers: \n");
   System.out.print("\tComputer games\n\tCoffee\n");
   System.out.print("\tAspirin");
   }
}   
class Variable{
   public static void main(String[]args)
   {
   int value;
   value = 5;
   System.out.print("The value is ");
   System.out.println(value);
   System.out.println("Hello" + " World");
   System.out.print("The value is: " + 5);
   System.out.print("The value is: " + value);
   System.out.print("The value is: " + '\n' + 5);
   }
}   
class string{
    public static void main(String[]args)/*must have a class, main is required in java*/
   {
   //tells System to use its output facilities and print the contents of the string
   // System.out.println("This line is too long and now it" + 
//    " has spanned more than one line, which will cause a" +
//    " syntax error to be generated by the compiler");
//    System.out.println("We can join a string to " +
//    "a number like this: " + 5);
      System.out.println("The following will be printed " +
                         "in a tabbed format: " +
                         "\n\tFirst = " + 5 * 6 + "," +
                         "\n\tSecond = " + (6 + 4) + "," +
                         "\n\tThird = " + 16.7 + ".");
   }
}
class Initialize{
   public static void main(String[] args) {
      int month = 2, days = 28;
      
      System.out.println("Month " + month + " has " + 
                        days + " days." );
      }
}
// class Math{
//    public static void main(String[] args){
//       int w = 5;
//       int x = 4;
//       int y = 8;
//       int z = 2;
//       int result;
//       result = x + y;
//       result = z * 2;
//       result = y / x;
//       result = y - z;
//       result = w % 2;
//       }
// }

   
class ScannerExample
{
   public static void main(String[] args)
   {
   String name;

   Scanner keyboard = new Scanner(System.in);
   
   System.out.print("What is your name? ");
   name = keyboard.nextLine();
   
   System.out.println("Hello " + name);
   }
}
class Name
{
   public static void main(String[] args)
   {
   String name;

   Scanner keyboard = new Scanner(System.in);
   System.out.print("What is your name? ");
   name = keyboard.nextLine();
   
   
   System.out.print("How many hours do you work? ");
   int hours = keyboard.nextInt();
     

   System.out.print("How much do you get paid? ");
   int pay = keyboard.nextInt();
   

   int gross = pay * hours;
   System.out.println(name + " " + gross);
   
   System.out.println("Hello " + name);
   }
}